config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart' 
  get '/cart/:id' => 'cart#add'

  resources :products
  root "page#home"

  get 'page/contact'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category

	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def add
  	id = params[:id]
  	# if the cart has already been created, use existing cart. Else create a new one.
  	if session[:cart] then
  		cart = session[:cart]
  	else
  		session[:cart] = {}
  		cart = session[:cart]
  	end

  	#if the product has already been added to the cart, increment the value by 1. Else set value to 1
  	if cart[id] then
  		cart[id] = cart[id] + 1
  	else
  		cart[id] = 1
  	end
  redirect_to :action => :index	
  end

  def clearCart
  	session[:cart] = nil
  	redirect_to :action => :index
  end

  def index
  	# if there is a cart, pass it to the page to display a cart. Else pass an empty value
  	if session[:cart] then
  		@cart = session[:cart]
  	else
  		@cart = {}
  	end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	before_action :authenticate_user!, except: [:home]
  def home
  end

  def about
  end

  def faqs
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  before_action :admin_validation, only: [:new, :edit, :destroy]
  before_action :authenticate_user!, only: [:index]

  def index
    if params[:category].blank?
      @products = Product.all
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def admin_validation
      if current_user.role !='admin'
        redirect_to root_path
      end
    end

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.haml
.row
  .col-md-offset-4.col-md-3
    .thumbnail
      .caption
        %h1 Your cart
        - if @cart.empty?
          %p Your cart currently empty.
        -else
          = link_to "Empty your cart", cart_clear_path
        %br
        - total = 0
        %ul
          - @cart.each do |id, quantity|
            - product = Product.find_by_id(id)
            %li
              = link_to product.title, product
              %p= product.description
              %p= number_to_currency(product.price, :unit => '$')
              %p 
                Quantity: #{quantity}
            - total += quantity *product.price
          %p 
            %b= number_to_currency(total, :unit => '$')       
            %b= link_to "Create Order", root_path, notice: 'Product was successfully updated.'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Cartapp
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body

%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %a.navbar-brand{:href => root_path} Cartapp
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          %li= link_to "Home", root_path
          %li= link_to "Contact", page_contact_path
          %li= link_to "Shop", products_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            =link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %li  
            =link_to "Sign In", new_user_session_path
          %li
            =link_to "Sign Up",  new_user_registration_path
    / /.navbar-collapse
  / /.container-fluid
= yield

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.haml
%div.jumbotron
  %h2 
    Contact us!
  %h3  
    %p
      Name: Arsen Ugliar
    %p
      E-mail: arsen.ugliar@gmail.com
    %br  
    %p
      Name: Ivan Nykyforuk
    %p
      E-mail: ivan@gmail.com
    %br  
    %p
      Name: Marcin Lubanski
    %p
      E-mail: marcin@gmail.com 
    %br   
      =link_to "Start shopping!", products_path, class:"btn btn-primary btn-lg"

app/views/page/faqs.html.erb
<h1>Page#faqs</h1>
<p>Find me in app/views/page/faqs.html.erb</p>

app/views/page/home.html.haml
%div.jumbotron
  %h1 
    Welcome to shopping cart!
  %p
    This is simple shopping cart for you and your family.
  %p
    =link_to "Start shopping!", products_path, class:"btn btn-primary btn-lg"

app/views/products/_form.html.haml
= form_for@product, html: {multipart: true} do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message
  %br       
  .field
    = f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"}
  .field
    = f.label :title
    %br
      = f.text_field :title
  .field
    = f.label :description
    %br
      = f.text_area :description
  .field
    = f.label :price
    %br
      = f.number_field :price
  .field
    = f.label :image
    %br
      = f.file_field :image   
  .actions
    = f.submit

app/views/products/edit.html.erb
<div class="col-md-offset-4 col-md-4">
<h1>Editing Product</h1>

<%= render 'form' %>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

</div>

app/views/products/index.html.haml
.row
  - @products.each do |product|
    .col-sm-4.col-md-3
      .thumbnail
        %img= image_tag product.image.url(:thumb)
        .caption
          - if current_user.role.nil?
            %h3= product.title
            %h4
            %p= product.category.name
            %p= number_to_currency(product.price, unit: "$")
            %p= product.description
            %p
              %a= link_to 'Show', product, class: "btn btn-default"
            %p
              %a.btn.btn-primary{:href => "/cart/#{product.id}", :role => "button"} Add to cart
          - else
            %h3= product.title
            %h4
            %p= product.category.name
            %p= number_to_currency(product.price, unit: "$")
            %p= product.description
            %p
              %a= link_to 'Show', product, class: "btn btn-default"
              %a= link_to 'Edit', edit_product_path(product), class: "btn btn-default"
              %a= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"
            %p
              %a.btn.btn-primary{:href => "/cart/#{product.id}", :role => "button"} Add to cart
- if current_user.role == "admin"              
  .btn
    %a= link_to 'New Product', new_product_path, class: "btn btn-success"

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.haml
.row
  .col-md-offset-4.col-md-3
    .thumbnail
      %img= image_tag @product.image.url(:medium)
      .caption
        %h3= @product.title
        %p= @product.description
        %p= number_to_currency(@product.price, unit: "$")
        = link_to 'Edit', edit_product_path(@product), class: "btn btn-primary"
        \#{link_to 'Back', products_path, class: "btn btn-primary"}